// <auto-generated />
namespace MyEngine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class MigrateDB101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigrateDB101));
        
        string IMigrationMetadata.Id
        {
            get { return "201603260626349_MigrateDB101"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
